// export * from './Account'

export * from './Detail'
export * from './Home'
export * from './Login'
export * from './Rap'
export * from './Register'
export * from './Account'
export * from './BookingPage'
export * from './SearchPage'